perturbnormal:
  input_shape: [128, 48]

perturbuniform:
  input_shape: [128, 48]

perturbtriangle:
  input_shape: [128, 48]

perturbrademacher:
  input_shape: [128, 48]

perturbeggroll:
  input_shape: [128, 48]

rqsperturbrademacher:
  input_shape: [128, 48]

rqsperturbuniform:
  input_shape: [128, 48]

conv2d:
  input_shape: [1, 1, 28, 28]
  kernel_size: 5
  out_channels: 16
  stride: 1
  padding: 0 
  use_bias: true
  group: 1
  dilation: 1